<template>
  <div>
    <iframe
      title="supplied-analyse"
      width="1100"
      height="600"
      src="https://app.powerbi.com/view?r=eyJrIjoiNmFjMWYwMjItNzM5ZS00MjFkLWFiZjktMDQ1MTczNjE4MzZjIiwidCI6ImU0OWRhNTdiLWI2MDItNDY2Ny1iMjU3LWYyMjgxOWUwZjA5MCIsImMiOjEwfQ%3D%3D&pageName=ReportSection"
      frameborder="0"
      allowFullScreen="true"
    ></iframe>
  </div>
</template>